
#####################################################################
#               Load, Process and Save Precipitation Data           #
#                               REIPAA                              #
#                                                                   #
# Homogenise time interval and Extract daily values when            #
# observation interval is higher. Also deal with NA values          #
#                                                                   #
# Author: PiM Lefeuvre                          Date: 2014-09-03    #
# Raw Data are resampled to provide regular time series             #
# Formerly, "eKlima/LoadPP_Reipaa_Daily_save.R"                     #
#####################################################################

###########################################
# Clean up Workspace
# rm(list = ls(all = TRUE))
###########################################

# Set Path
setwd(path.wd)
Sys.setenv(TZ="UTC")  

# Load libraries
library(chron)
library(hydroTSM)   # cmd: izoo2rzoo
library(zoo)

# Load User functions
source("../../UserFunction/subsample.R")
source("../../UserFunction/axPOSIX.R")  
source("../../UserFunction/remove_col.R")


############################################
# Load data
Raw1995         <- read.csv("Raw/Reipaa_TP_1995-1996.txt",sep=';',
                            as.is=T,skip=30,header=T,blank.lines.skip=T)
Raw1996         <- read.csv("Raw/Reipaa_TP_1996-1998.txt",sep = ';',
                            as.is=T,skip=26,header=T,blank.lines.skip=T)
Raw1998         <- read.csv("Raw/Reipaa_TP_1998-2000.txt",sep = ';',
                            as.is=T,skip=26,header=T,blank.lines.skip=T)
Raw2000         <- read.csv("Raw/Reipaa_TP_2000-2002.txt",sep = ';',
                            as.is=T,skip=26,header=T,blank.lines.skip=T)
Raw2002         <- read.csv("Raw/Reipaa_TP_2002-2004.txt",sep = ';',
                            as.is=T,skip=26,header=T,blank.lines.skip=T)
Raw2004         <- read.csv("Raw/Reipaa_TP_2004-2006.txt",sep = ';',
                            as.is=T,skip=26,header=T,blank.lines.skip=T)
Raw2006         <- read.csv("Raw/Reipaa_TP_2006-2008.txt",sep = ';',
                            as.is=T,skip=26,header=T,blank.lines.skip=T)
Raw2008         <- read.csv("Raw/Reipaa_TP_2008-2010.txt",sep = ';',
                            as.is=T,skip=33,header=T,blank.lines.skip=T)
Raw2010         <- read.csv("Raw/Reipaa_TP_2010-2012.txt",sep = ';',
                            as.is=T,skip=26,header=T,blank.lines.skip=T)
Raw2012         <- read.csv("Raw/Reipaa_TP_2012-2014.txt",sep = ';',
                            as.is=T,skip=28,header=T,blank.lines.skip=T)


# Remove tail, which is some text generated by eKlima (2 lines) 
# NOTE: sometimes more to avoid overlap between two years
Raw1995             <- Raw1995[1:(nrow(Raw1995)-5),]
Raw1996             <- Raw1996[1:(nrow(Raw1996)-2),]
Raw1998             <- Raw1998[1:(nrow(Raw1998)-2),]
Raw2000             <- Raw2000[1:(nrow(Raw2000)-2),]
Raw2002             <- Raw2002[1:(nrow(Raw2002)-2),]
Raw2004             <- Raw2004[1:(nrow(Raw2004)-2),] 
Raw2006             <- Raw2006[1:(nrow(Raw2006)-2),]
Raw2008             <- Raw2008[1:(nrow(Raw2008)-8),]
Raw2010             <- Raw2010[1:(nrow(Raw2010)-2),] 
Raw2012             <- Raw2012[1:(nrow(Raw2012)-5),] #Ends 2013/02/01 24:00

# Combine all Data
Raw             <- rbind(Raw1995,Raw1996,Raw1998,Raw2000,Raw2002,Raw2004,
                         Raw2006,Raw2008,Raw2010,Raw2012)
class(Raw)

# Clear memory
# rm(Raw1995,Raw1996,Raw1998,Raw2000,Raw2002,Raw2004,Raw2006,Raw2008,Raw2010,Raw2012)

# Replace "x" (Very uncertain data) by NA.
Raw$RR_24[Raw$RR_24=="x"]   <- NA
Raw$RR_12[Raw$RR_12=="x"]   <- NA

# Convert charachter into numeric
Raw$RR_24       <-as.numeric(Raw$RR_24)
Raw$RR_12       <-as.numeric(Raw$RR_12)

############################################
############################################
# PROCESSING NA and Zero VALUES

# Remove NA values
is.na(Raw)      <- (Raw == -9999)
# The eKlima drift told me that -1 in these conditions mean that the instrument
# has measured nothing because it didn't rain.
Raw[Raw==(-1)]  <- 0
# Remove empty data columns (containing only NA)
Output      <- remove_col(Raw)
list2env(Output,env=environment())
rm(Output)


############################################
############################################
## DATES

# Format Dates in POSIXlt - POSIXct
Dates         <- as.POSIXct(strptime(paste(Raw$Year,Raw$Mnth,
                                           Raw$Date, Raw$Time.NMT.),
                                     "%Y %m %d %H"))
class(Dates)


############################################
############################################
# Transform in zoo object. Remove the column "Dates" because replaced by order.by and the column Water_level2 because the data do not show anything interesting (only 2009-2010)
lcol            <- ncol(Raw)
ts.Raw          <- zoo(x=Raw$RR_24, order.by=Dates)

############
# SUBSAMPLING
sub.start         <- "1992-001"
sub.end           <- "2014-001"
ts.sub          <- subsample(ts.Raw,sub.start,sub.end,F)


############
# Regularly spaced zoo
ts.reg          <- izoo2rzoo(ts.sub,date.fmt="%Y-%m-%d %H:%M:%S", tstep="hour")

# # Approximate only when the gap (No Values) is one hour only.
# ts.reg          <- na.approx(ts.reg,maxgap=1)  

### Extract one value per day (every 24h). The record starts at 07:00.
ts.reg.d         <- ts.reg[seq(1,length(ts.reg),24)]


############################################
# PLOT 1
ymax = 100

plot(ts.sub, type="h", main="Precipitation from Reipaa Weather Station",
     col="blue", xlab="Time [year]",ylab="Precipitation [mm]",
     xaxt="n",ylim=c(0,ymax))
lines(ts.reg.d,type="h",col="red",lwd=0.5)

# Time axis
axPOSIX(ts.sub,"years","%Y")

############################################
############################################
# SAVE
# Save data in zoo format
path <- "../../Processing/Data/MetData/Precip" 
write.zoo(ts.reg,file=sprintf("%s/Reipaa_P24_full.csv",path),sep=",")


### ARCHIVE


