
#####################################################################
#             Load, Process and Save Air Temperature Data           #
#                           GLOMFJORD                               #
#                                                                   #
# Homogenise time interval and Extract daily values when            #
# observation interval is higher. Also deal with NA values          #
#                                                                   #
# Author: PiM Lefeuvre                          Date: 2014-09-03    #
# Raw Data are resampled to provide regular time series             #
#####################################################################

###########################################
# Clean up Workspace
# rm(list = ls(all = TRUE))
###########################################

# Set Path
setwd(path.wd)
Sys.setenv(TZ="UTC")  

# Load libraries
library(zoo)
library(chron)
library(hydroTSM)   # cmd: izoo2rzoo


# Load User functions
source("../../UserFunction/subsample.R")
source("../../UserFunction/axPOSIX.R")  
source("../../UserFunction/remove_col.R")


############################################
# Load data
Raw1990         <- read.csv("Raw/Glomfjord_T_1990-1992.txt",sep=';',
                            as.is=T,skip=25,header=T,blank.lines.skip=T);
Raw1992         <- read.csv("Raw/Glomfjord_T_1992-1994.txt",sep=';',
                            as.is=T,skip=25,header=T,blank.lines.skip=T);
Raw1994         <- read.csv("Raw/Glomfjord_T_1994-1996.txt",sep=';',
                            as.is=T,skip=25,header=T,blank.lines.skip=T);
Raw1996         <- read.csv("Raw/Glomfjord_T_1996-1998.txt",sep=';',
                            as.is=T,skip=31,header=T,blank.lines.skip=T);
Raw1998         <- read.csv("Raw/Glomfjord_T_1998-2000.txt",sep=';',
                            as.is=T,skip=29,header=T,blank.lines.skip=T);
Raw2000         <- read.csv("Raw/Glomfjord_T_2000-2002.txt",sep=';',
                            as.is=T,skip=29,header=T,blank.lines.skip=T);
Raw2002         <- read.csv("Raw/Glomfjord_T_2002-2004.txt",sep=';',
                            as.is=T,skip=29,header=T,blank.lines.skip=T);
Raw2004         <- read.csv("Raw/Glomfjord_T_2004-2006.txt",sep=';',
                            as.is=T,skip=29,header=T,blank.lines.skip=T);
Raw2006         <- read.csv("Raw/Glomfjord_T_2006-2008.txt",sep=';',
                            as.is=T,skip=24,header=T,blank.lines.skip=T);
Raw2008         <- read.csv("Raw/Glomfjord_T_2008-2010.txt",sep=';',
                            as.is=T,skip=24,header=T,blank.lines.skip=T);
Raw2010         <- read.csv("Raw/Glomfjord_T_2010-2012.txt",sep=';',
                            as.is=T,skip=29,header=T,blank.lines.skip=T);


# Remove tail, which is some text generated by eKlima (2 lines) NOTE: -5 to avoid overlap between two years
Raw1990             <- Raw1990[1:(nrow(Raw1990)-5),]
Raw1992             <- Raw1992[1:(nrow(Raw1992)-5),]
Raw1994             <- Raw1994[1:(nrow(Raw1994)-5),]
Raw1996             <- Raw1996[1:(nrow(Raw1996)-32),]
Raw1998             <- Raw1998[1:(nrow(Raw1998)-29),]
Raw2000             <- Raw2000[1:(nrow(Raw2000)-29),]
Raw2002             <- Raw2002[1:(nrow(Raw2002)-32),]
Raw2004             <- Raw2004[1:(nrow(Raw2004)-32),]
Raw2006             <- Raw2006[1:(nrow(Raw2006)-26),]
Raw2008             <- Raw2008[1:(nrow(Raw2008)-26),]
Raw2010             <- Raw2010[1:(nrow(Raw2010)-5),]


# Combine all Data
Raw             <- rbind(Raw1990,Raw1992,Raw1994,Raw1996,Raw1998,Raw2000,
                         Raw2002,Raw2004,Raw2006,Raw2008,Raw2010)

# Clear memory
# rm(Raw1990,Raw1992,Raw1994,Raw1996,Raw1998,Raw2000,Raw2002,Raw2004,Raw2006,
#    Raw2008,Raw2010)

# Replace "x" (Very uncertain data) by NA.
Raw$TA[Raw$TA=="x"] <- NA

# Convert charachter in numeric after changing comas into points
Raw$TA          <-as.numeric(Raw$TA)

############################################
############################################
# PROCESSING NA and Zero VALUES

# Remove NA values
is.na(Raw)      <- (Raw == -9999)
# Remove empty data columns (containing only NA)
Output      <- remove_col(Raw)
list2env(Output,env=environment())
rm(Output)


############################################
############################################
## DATES

# Format Dates in POSIXlt - POSIXct
Dates         <- as.POSIXct(strptime(paste(Raw$Year,Raw$Mnth,
                                           Raw$Date, Raw$Time.NMT.),
                                     "%Y %m %d %H"))
class(Dates)


############################################
############################################
# Transform in zoo object. Remove the column "Dates" because replaced by order.by and the column Water_level2 because the data do not show anything interesting (only 2009-2010)
lcol            <- ncol(Raw)
ts.Raw          <- zoo(x=Raw$TA, order.by=Dates)

############
# SUBSAMPLING
sub.start       <- "1990-001"
sub.end         <- "2012-001"
ts.sub          <- subsample(ts.Raw,sub.start,sub.end,F)

############
# Regularly spaced zoo
ts.reg          <- izoo2rzoo(ts.sub,date.fmt="%Y-%m-%d %H:%M:%S", tstep="hour")

# # Approximate only when the gap (No Values) is one hour only.
# ts.reg          <- na.approx(ts.reg,maxgap=1)  

############################################
# Plot
plot(ts.reg, type="p", col="orange3",pch=".",xaxt="n",
     main="Air Temperature from Glomfjord", 
     xlab="Time [year]",ylab="Temperature [C]")
abline(h=0,lty=3)

# Time axis
axPOSIX(ts.sub,"years","%Y")

############################################
############################################
# Save data in zoo format
path <- "../../Processing/Data/MetData/AirTemp" 
write.zoo(ts.reg,file=sprintf("%s/Glomfjord_AT_1hr_full.csv",path),sep=",")




### ARCHIVE